config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :songs

  authenticated :user do
    root :to => 'songs#index'
  end
  # root :to => "users#index"
  # devise_for :users
  # resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/song.rb
class Song < ActiveRecord::Base
  include Authority::Abilities
  resourcify
  belongs_to :user, class_name: 'User'

  # attr_accessible :parsed, :body, :title, :user_id
  validates :title, :body, :presence => true
  before_update :parse_with_save


  def parse_with_save
    self.parsed = SongParser.new.initialize_with_attr(self.id, self.body)
    true
  end

  def parse
    SongParser.new.initialize_with_attr(self.id, self.body)
  end

end

class SongParser

  attr_accessor :input
  attr_accessor :output

  def header
    begin
      output.clear
      title = @input.shift().delete('**').strip
      artist = @input.shift().delete('**').strip
      notes = @input.shift().delete('**').strip

      output << "\\section{#{title} / #{artist}}\\label{sec:#{title.downcase.gsub(/[^a-z0-9]+/i, '_')}}\n"
      unless notes.empty?
        output << "{\\small #{notes}}\n"
      end
    rescue StandardError => e
      Rails.logger.error(e)
      output.clear
      output << "[ERROR] Your song is not yet written and formatted correctly.\n---\n"
    ensure
      output
    end
  end

  def chords
    begin
      space
      process = @input.take_while { |arr| arr != "chords **" }
      process.delete_at(0)
      process.each do |chord|
        output << "\\#{chord}\n"
        @input.delete(chord)
      end
      @input.slice!(0..1)
    rescue StandardError => e
      Rails.logger.error(e)
      output.clear
      output << "[ERROR] Your song is not yet written and formatted correctly.\n---\n"
    end
  end

  def lyrics
    begin
      space

      @input.each do |lyric|
        unless lyric.nil? || lyric.strip == "**"
          output << lyric.gsub(/[\[]/, '\upchord{').gsub(/[\]]/, '}').gsub(/---/, '\hrulefill') + "\n\n"
        end
      end
    rescue StandardError => e
      Rails.logger.error(e)
      output.clear
      output << "[ERROR] Your song is not yet written and formatted correctly.\n---\n"
    end
  end

  def space
    output << "\n"
  end

  def initialize
    @input = Array.new
    @output = Array.new
  end

  def initialize_with_attr(id, body)
    # create temporary file
    filename = "#{id}_#{SecureRandom.uuid}"
    file = File.new(filename, 'w+')
    file.write(body)
    file.close
    f = File.open(filename, 'r')
    f.each { |line|
      unless line.strip.empty?
        @input.push(line.strip)
      end
    }
    r = File.delete(filename)

    @input.collect! { |line| line[0..1] != "//" ? line : nil }
    @input.delete_if { |x| x == nil }

    header
    chords
    lyrics

    @output
  end

  def initialize_with_file(filepath)
    file = File.open(filepath, 'r')
    file.each { |line|
      unless line.strip.empty?
        @input.push(line.strip)
      end
    }

    @input.collect! { |line| line.strip! unless line[0..1] == '//' }
    @input.delete_if { |x| x == nil }

    header
    chords
    lyrics
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  include Authority::UserAbilities
  rolify

  # attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :songs, foreign_key: :user_id

  def nickname
    "#{(self.name.nil? ? self.name : self.email.split('@')[0])} #{self.id.to_s}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all # This is now fetched by Cancan
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    @parsed = @song.parse()

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new
    @method = "POST"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
    @method = "PUT"
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = current_user.songs.build(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_path(@song), notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render json: @song }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/index.html.erb
<h3>Welcome to the Balham Ukesoc Songsheet Maker</h3>
<p>This application converts songs from the generic song spec into LaTeX-code for typsetting into the bigger songbooks.</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Balham Ukesoc Songsheet Maker", root_path, :class => 'brand' %>
<ul class="nav nav-tabs">
  <% if user_signed_in? %>
      <li>
        <%= link_to 'Songs', songs_path %>
      </li>
      <% if current_user.has_role? :admin %>
          <li>
            <%= link_to 'Admin', users_path %>
          </li>
      <% end %>
  <% else %>
      <li>
        <%= link_to 'Sign up', new_user_registration_path %>
      </li>
  <% end %>
  <% if user_signed_in? %>
      <li>
        <%= link_to "[#{current_user.id}: #{current_user.email}] - Edit account", edit_user_registration_path %>
      </li>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, :method => 'delete' %>
      </li>
  <% else %>
      <li>
        <%= link_to 'Login', new_user_session_path %>
      </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Songsheet Maker" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Songsheet Maker" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/songs/_form.html.erb
<div class="row">
  <div class="span12">
    <%= simple_form_for(@song) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :title %>
          <div class="boxes">
            <pre id="song_parse" class="scroll_2 pre-scrollable" style="float:right"></pre>
            <%= f.input :body, as: :text %>
          </div>
        </div>

        <div class="form-actions">
          <button class="btn btn-warning btn-large" type="submit">Update Song</button>
        </div>
    <% end %>
  </div>
</div>

app/views/songs/edit.html.erb
<h3 id="editing_song_title">Editing song</h3>

<%= render 'form' %>

<div class="btn-group">
<%= link_to 'Show Song', @song, :class => "btn btn-success" %> |
<%= link_to 'List of Songs', songs_path, :class => "btn btn-success" %>
</div>

app/views/songs/index.html.erb
<h3>Listing your songs</h3>

<% if @songs %>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Title</th>
        <th colspan="4">Owner</th>
      </tr>
      <% @songs.each do |song| %>
          <tr>
            <td><%= song.title %></td>
            <td>
              <% if song.user == current_user %>
                  You
              <% else %>
                  User #<%= song.user.id %>
              <% end %>
            </td>
            <td><%= link_to 'Show', song, :class => "btn btn-success" %></td>
            <td>
              <% if song.updatable_by?(current_user) %>
                  <%= link_to 'Edit', edit_song_path(song), :class => "btn btn-warning" %>
              <% end %>
            </td>
            <td>
              <% if song.deletable_by?(current_user) %>
                  <%= link_to 'Destroy', song, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger" %>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
<% end %>

<br/>

<%= link_to 'Create a New Song', new_song_path, :class => "btn btn-success" %>

app/views/songs/new.html.erb
<h3>New song</h3>

<%= render 'form' %>

<%= link_to 'Cancel and go back to List', songs_path, :class => "btn btn-success" %>

app/views/songs/show.html.erb
<h3 id="editing_song_title">
  <% unless @song.title.nil? %>
      <%= @song.title %>
  <% end %>
</h3>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span12">
    <div class="boxes">
      <pre id="song_parse_show" class="scroll_2 pre-scrollable" style="float:right"><% @parsed.each do |line| %><%= line.strip << "\n  " %><% end %></pre>
      <pre id="song_body" class="pre-scrollable"><%= @song.body %></pre>
    </div>

    <div class="btn-group">
      <%= link_to 'Edit this Song', edit_song_path(@song), :class => "btn btn-warning" %> |
      <%= link_to 'List of Songs', songs_path, :class => "btn btn-success" %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>